"""create_homepage_stats_table

Revision ID: ea24dc931c5f
Revises: 0005_partial_unique_indexes
Create Date: 2026-06-14 19:37:24.302889
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea24dc931c5f'
down_revision = '0005_partial_unique_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_stats_id'), 'homepage_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_stats_id'), table_name='homepage_stats')
    op.drop_table('homepage_stats')
    # ### end Alembic commands ###

